name: CI SQUAD-RUN

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    container:
      image: php:8.4-cli
    steps:
      - uses: actions/checkout@v4

      - name: Instalando dependências do sistema
        run: |
          apt-get update -yqq
          apt-get install -yqq git unzip libzip-dev libpng-dev libonig-dev
          docker-php-ext-install pdo pdo_mysql zip

      - name: Instalando Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer

      - name: Copiando .env file
        run: cp .env.example .env

      - name: Instalando dependências
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Gerando chave da aplicação
        run: php artisan key:generate

      - name: Permissões de diretório
        run: |
          chmod -R 777 storage
          chmod -R 777 bootstrap/cache

      - name: Executando testes
        run: vendor/bin/phpunit --testdox
