name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v4

      - name: Copy .env file
        run: cp .env.example .env

      - name: Start Docker Containers
        run: docker compose up -d

      - name: Install dependencies
        run: docker compose exec -T squadrun_app composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate application key
        run: docker compose exec -T squadrun_app php artisan key:generate

      - name: Directory permissions
        run: |
          docker compose exec -T squadrun_app chmod -R 777 storage
          docker compose exec -T squadrun_app chmod -R 777 bootstrap/cache

      - name: Run migrations
        run: docker compose exec -T squadrun_app php artisan migrate --force

      - name: Run tests
        run: docker compose exec -T squadrun_app vendor/bin/phpunit --testdox

      - name: Stop Containers
        if: always()
        run: docker compose down
